name: six_jar
description: "Six Jar money management app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # screen util
  flutter_screenutil: ^5.9.3

  # router
  go_router: ^15.1.2

  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Utilities
  equatable: ^2.0.7

  # UI
  flutter_svg: ^2.1.0

  # API
  dio: ^5.8.0+1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # dot env
  flutter_dotenv: ^5.2.1

  # logger
  logger: ^2.5.0

  # smooth page indicator
  smooth_page_indicator: ^1.2.1

  # Currency Picker
  currency_picker: ^2.0.21

  # internet checker
  connectivity_plus: ^6.1.4

  # Charts 
  fl_chart: ^1.0.0

  # Package info plus 
  package_info_plus: ^8.3.0

  # Cached network image 
  cached_network_image: ^3.4.1

  # Lottie 
  lottie: ^3.3.1

  # intl 
  intl: ^0.20.2

  # badge 
  badges: ^3.1.2

  # firebase 
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4

  # Mongo DB 
  mongo_dart: ^0.10.5

  # google sign in 
  google_sign_in: ^6.3.0

  # json annotation 
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # change package name 
  change_app_package_name: ^1.5.0

  # injectable generator
  injectable_generator: ^2.7.0

  # json serializable 
  json_serializable: ^6.9.5

  # build runner
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/jpg/
    - assets/lottie/
    - assets/font/Poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
