name: six_jar
description: "Six Jar money management app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0-76.0.dev

dependencies:
  flutter:
    sdk: flutter

  # screen util
  flutter_screenutil: ^5.9.3

  # router
  go_router: ^15.1.2

  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Utilities
  equatable: ^2.0.7

  # UI
  flutter_svg: ^2.1.0

  # API
  retrofit: ^4.4.2
  dio: ^5.8.0+1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # dot env
  flutter_dotenv: ^5.2.1

  # logger
  logger: ^2.5.0

  # smooth page indicator
  smooth_page_indicator: ^1.2.1

  # Currency Picker
  currency_picker: ^2.0.21

  # internet checker
  connectivity_plus: ^6.1.4

  # Charts 
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # retrofit generator
  retrofit_generator: ^9.2.0

  # injectable generator
  injectable_generator: ^2.7.0

  # build runner
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/font/Poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
